from pathlib import Path
import json,hashlib,re,collections
P=Path(__file__).resolve().parent;RUN=P.parent;ROOT=P.parents[5]
SOURCE=RUN/'terra-full-v2/assembled/manuscript.md';SHA='e641f3b639f0c03578c51916c0434156c584ce8022f556d94e522bf7c653679d'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rd(p):return json.loads(p.read_text(encoding='utf-8'))
def save(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
assert sha(SOURCE)==SHA
paragraphs=SOURCE.read_text(encoding='utf-8').strip().split('\n\n');assert len(paragraphs)==1894
loc={};ranges=[];ch=0
for i,t in enumerate(paragraphs,1):
 m=re.match(r'# Розділ (\d+)',t)
 if m:
  ch=int(m[1]);ranges.append(dict(chapter=ch,first_paragraph=i,last_paragraph=i))
 ranges[-1]['last_paragraph']=i;loc[i]=dict(chapter=ch,anchor=f'P{i:05d}',quote=t)
assert len(ranges)==36
# All decisions below were made after actual complete sequential reread, not keyword triage.
DATA=[]
def add(orig,cat,sev,certainty,ps,title,why,decision,direction='',deps=None):
 DATA.append(dict(orig=orig,cat=cat,sev=sev,certainty=certainty,ps=ps,title=title,why=why,decision=decision,direction=direction,deps=deps or []))
add(['terra:final:1','gemini_flash:final:4.1','gemini_pro:final:2','root:ROOT-TERRA-07'],'prose','minor','confirmed_conflict',[1026],'Зайва ц у двадццять','Точний одрук є в джерелі; Flash помилково описує три ц, насправді дві.','compatible_correction','Виправити тільки двадццять → двадцять.')
add(['gemini_flash:final:4.2:1'],'prose','minor','confirmed_conflict',[133],'Мені не попросила нічого','Адресат попередньої просьби Тарас; Даль не отримав просьби. Давальний тут ламає саме цю синтаксичну будову.','compatible_correction','Природно передати, що Іра ні про що не попросила Даля; не додавати образи чи іншого доручення.')
add(['gemini_pro:final:1'],'prose','minor','confirmed_conflict',[1041],'Заважати ложкою','Контекст — обертання води після помішування, не створення перешкоди. Образ придатний, дієслово неточне.','compatible_correction','Зберегти образ води, яку перестали мішати ложкою; змінити тільки невдале дієслово/його зв’язок.')
add(['gemini_pro:final:3','gemini_pro:turn-002:1','root:ROOT-TERRA-10'],'clarity','minor','strong_inference',[1119],'Друга година ночі й спостережений час','Контекст однієї доби визначає02:00, але еліпсис допускає миттєве читання другої ночі. Метадані помилково кажуть без точного годинника і закінчують план о02.','compatible_correction','Додати години в після другої години ночі. У нових станах явно записати, що частина сцени після02:00; плановий інтервал не видавати за фактичну межу.',['CH20 time_basis','CH21 sleep then arrival after07'])
add(['root:ROOT-TERRA-02','astra:full_read'],'continuity','moderate','confirmed_conflict',[544,561,563,564],'Та сама чергова відмовляє двічі','На засіданні Вектор уже дочекався відмови через нічну роботу, потім у коридорі дізнається її вперше й знову викреслює.','compatible_correction','У ранньому абзаці лишити спробу перенести людину/надіслане питання з відповіддю ще pending. Пізнішу розмову й викреслення зберегти як єдине отримання відмови. Не вигадувати другої людини.',['CH10 one gap remains','staffing stateCH09'])
add(['root:ROOT-TERRA-03'],'continuity','moderate','confirmed_conflict',[715,499,785],'Учорашня суперечка','СуперечкаCH08D2, монтажнаCH12D4. У суботуCH14 попередній день прямо пов’язано з Ірою.','compatible_correction','Назвати попередню записану суперечку без хибного вчора або правильно позавчора. Не переносити монтаж на інший день.',['D2 debate','D4 withdrawal','D5 privatechoice'])
add(['root:ROOT-TERRA-04','root:ROOT-TERRA-08'],'continuity','moderate','confirmed_conflict',[1003,1047,1013,1596],'Два передстартові завтра означають неправильний день повернення','Обидві репліки перед недільною північчю. Завтра00:00 — понеділковий запуск, а не вівторкове повернення через24год.','compatible_correction','У CH18 прямо понеділок00:00 старт і вівторок00:00 повернення; у CH19 відповідь про повернення прямо вівторок00:00. Зберегти рівно24год і таймер.',['CH18/19/30 time states','D6→D7→D8'])
add(['root:ROOT-TERRA-11'],'continuity','moderate','confirmed_conflict',[1612,1610,1641,1707],'Запрошення після півночі','CH30 вже вівторок00:30; звітCH31того самого вівторка, потімCH32обіцяє середу. Завтра зсуває весь фінал.','compatible_correction','Запрошення на сьогодні/удень о дванадцятій, не завтра. Решту репліки лишити.',['CH30/31/32 chronology'])
add(['root:ROOT-TERRA-05'],'format','minor','confirmed_conflict',[786,793,1854],'Кириличний А у службовій назві','Параметри маршруту мають зіставлятися буквально. У По А стоїть U+0410, далі LatinA.','compatible_correction','Замінити тільки літеру службового маршруту А на латинську A. Українські літери поза ідентифікаторами не чіпати.',['CH07/10/14/17DOC/35/36 identifiers'])
add(['root:ROOT-TERRA-06'],'clarity','minor','strong_inference',[774],'Ніби завтра вимкнуть повідомлення','Це опис хибного враження від чернетки, не твердження про фактичне вимкнення. Однак завтра в п’ятничній сцені без потреби збиває графік понеділка.','compatible_correction','Прибрати хибну відносну дату, назвати час досліду/експериментальну добу. Зберегти ніби й факт виправлення оманливого тексту.',['D4→D7','display vs delivery'])
add(['root:ROOT-TERRA-12'],'voice','minor','strong_inference',[1612,1615],'Вектор: Прийдете → Бачив','У межах однієї розмови й надалі Вектор тримає ви; немає сценічного переходу, на відміну від Тараса.','compatible_correction','Зберегти формальне звертання в короткому питанні Вектора про оплески. Не додавати пояснювального абзацу.')
add(['root:ROOT-TERRA-13'],'voice','minor','taste',[612,1373,1375,1422,1757],'Тарасове ти в приватній домовленості','Приватне Не роби вжеCH11. Повернення до формального звертання в робочих сценах можливе; CH25і34 особистіші. Це не механічна помилка узгодження.','preserve_context','Не уніфікувати весь зв’язок на ви. Зберегти поступове особисте зближення.')
add(['root:ROOT-TERRA-09','astra:full_read'],'clarity','minor','strong_inference',[1272,1545,1717,1738],'Дві передачі деталей столу недостатньо розрізнені','У понеділок одержувачка забрала придатне у Лани; у середу чоловік отримує деталі у Тараса. Це можуть бути різні справи, не доведена повторна видача. Проте решти та повтор двох зайвих кріплень склеюють їх у пам’яті.','compatible_clarification','Мінімально розрізнити середовий запит як інший стіл/інший погоджений пакунок у CH29 і підтримати цей референтCH33. Не скасовувати понеділкову передачу й не оголошувати встановленою помилку подвійної видачі. Не вводити нові імена чи сцени.',['CH23/29/31/33 resources','working implementation not authorfact'])
add(['root:ROOT-TERRA-14','astra:full_read'],'continuity','minor','strong_inference',[1660,1390,1412,1419],'Посеред включення замість перед початком','Вектор може риторично перебільшувати, але буквальний час сприймається як пам’ять проCH26; там Даль відмовляється до старту. Перебільшення не потрібне для його аргументу.','compatible_correction','Зберегти образу/суху іронію Вектора й реальну ціну відмови, уточнивши перед самим включенням/в останню мить. Не робити Даля учасником уже розпочатого ефіру.',['CH26 source knowledge','CH31 state'])
add(['gemini_flash:final:4.3:decision'],'prose','minor','strong_inference',[802],'Рішення не зробленим','Незручна сполучуваність у відкладеній відповіді. Потрібна локальна природність, не переписування моральної сцени.','compatible_correction','Передати, що ненадіслана відповідь дозволяє вважати рішення ще не ухваленим/не остаточним; зберегти самообман Даля.')
add(['gemini_flash:final:4.3:guise'],'prose','minor','strong_inference',[1420],'Під виглядом того що','Важка конструкція біля сильного виходу. Можна компактно назвати удавання забутої речі без нормативного ярлика калька.','compatible_correction','Локально природно передати можливість повернутися, удаючи, ніби щось забув. Не змінювати факт виходу до ефіру.')
add(['gemini_pro:final:5'],'prose','minor','strong_inference',[1358],'Дата стояла п’ятницею','Дата/дія названі важко. Треба зберегти стару зовнішню публікацію до відкликання і новий понеділковий репост.','compatible_correction','Природно назвати первинну п’ятничну дату старої копії без зміни її походження й двох моментів поширення.',['Ira oldcopy not Vectorbreach'])
add(['gemini_flash:final:4.4'],'format','minor','confirmed_conflict',[1667],'Апостроф у назвіCH32','Прямий ASCIIапостроф відрізняється від загального типографічного стилю назв. Цитата Flash включає маркер заголовка неточно, потрібний рядок є.','compatible_correction','У назві Залишити ім’я уніфікувати типографічний апостроф. Не змінювати текст назви.')
add(['gemini_flash:final:4.3:pretend'],'prose','minor','taste',[720,740],'Зробити вигляд','Зрозуміла поширена конструкція; походження від іншої мови не доводить дефект. Компактне вдати може поліпшити два внутрішні речення, але не потрібна обов’язкова пуристична заміна.','preserve_context','Залишити у фінальному мінімальному пакеті; Terra не мусить застосовувати несумісні нормативні ярлики.')
add(['gemini_flash:final:4.2:lean'],'prose','minor','taste',[1674],'Спер її об стіну','Фізична дія зрозуміла. Висока впевненість рецензента не доводить ненормативності; словникової заборони не встановлено.','preserve_context','Не виправляти як підтверджену кальку; прихилив до стіни лише можлива необов’язкова редакторська альтернатива.')
add(['gemini_flash:final:4.2:drop'],'prose','minor','taste',[1752],'Тарас упустив ніж','Рецензент описує попередній голосний, але Тарас закінчується приголосним. Дія падіння ножа однозначна в наступному абзаці.','reviewer_noise','Зберегти. Не вигадувати порушення милозвучності й не замінювати всі упустив.')
add(['gemini_flash:final:4.3:acceptdecision'],'prose','minor','taste',[529],'Приймати рішення і заперечення','Не підтверджено заборону приймати рішення. Рішення в однині має ту саму форму родового; загальна вимога рецензента змінити ще й число необґрунтована.','reviewer_noise','Зберегти технічний голос Ренати, не робити глобальної заміни.')
add(['gemini_pro:final:4'],'prose','minor','taste',[1229],'Суперечка витратила день','Зрозуміле уособлення: чужий спір забирає ресурс жінки. Подібна предметність належить голосу Даля; буквальний агент не обов’язковий для метафори.','preserve_context','Зберегти; забрала — необов’язковий смак, не фактичне виправлення.')
add(['gemini_pro:final:6'],'voice','minor','taste',[1821,1829],'Еліпсис Ренати: раніше немає','Об’єкт прямо названо в попередньому реченні і наступному. Стисла усна відповідь не губить межі перевіреного журналу.','preserve_context','Зберегти живий еліпсис. Не додавати значення про відсутність усіх резервів.')
add(['gemini_pro:final:7'],'prose','minor','taste',[1824],'Вектору / Векторові','Рецензент сам визнає форму допустимою. Варіант закінчення не змінює адресата, голос чи зміст.','preserve_context','Не вводити механічну уніфікацію давального.')
add(['gemini_flash:final:4.5:1','gemini_pro:turn-001:3','root:native01-06:remaining'],'voice','minor','taste',[5],'Робити побут і дев’ять проміжних днів','Процедурність відображає героя після виходу. Календарна фраза трохи службова, але утримує явний пропуск часу; не руйнує сцену.','preserve_context','Зберегти як голос/місток; не оголошувати новим канонічним датуванням.')
add(['gemini_flash:final:4.5:2'],'voice','minor','taste',[105],'Замість робити своє','Еліпсис Іри природний для роздратованої короткої репліки, розгортання послабить удар.','preserve_context','Зберегти.')
add(['gemini_flash:final:4.5:3'],'voice','minor','taste',[1464],'Закрив рота','Конкретна зупинка власного виправдання працює; пуристичного виправлення сцена не потребує.','preserve_context','Зберегти.')
add(['gemini_flash:final:4.5:4'],'voice','minor','taste',[1052],'Стаканчик','Звичайна міська предметність; паперове горнятко не є обов’язковим поліпшенням.','preserve_context','Зберегти.')
add(['gemini_flash:turn-001:leaf'],'voice','minor','taste',[48],'Листок і аркуш','Ремарка оповідача й репліка Тараса не зобов’язані однаковому словнику; референт очевидний.','preserve_context','Зберегти.')
add(['gemini_flash:turn-001:need'],'prose','minor','taste',[388],'Забирала б потребу','Потреба Вектора зберігається всупереч точній перевірці; метафорична дієслівність читається без фактичної двозначності.','preserve_context','Зберегти; це не доведений дефект.')
add(['gemini_flash:turn-002:jacket'],'voice','minor','taste',[942],'Надів куртку','Не доведено потреби міняти звичайний міський словник. Немає зміни того, що герой одягнувся перед виходом.','preserve_context','Зберегти без глобального словникового правила.')
add(['gemini_flash:turn-003:eleven'],'prose','minor','taste',[1539],'Лежало одинадцять рядків','Рецензент сам визнає узгодження допустимим; сухий підрахунок доречний.','preserve_context','Зберегти.')
add(['gemini_pro:turn-001:1'],'prose','minor','taste',[7],'Не вимагала пояснити','Вказує на конкретне пояснення, якого робота не потребувала; рецензент обговорює перевагу конструкції, не встановлює втрату змісту.','preserve_context','Не робити обов’язковим перехід на віддієслівний іменник.')
add(['gemini_pro:turn-001:2'],'clarity','minor','strong_inference',[475,476,478],'Адреса зустрічі й домашня адреса для обходу','Відмова дати адресу не означає, що вони ніколи не бачили жінку. Але формула на другій адресі легко створює саме домашній поріг. Потрібно розвести фізичну зустріч та дозвіл записувати місце для майбутнього обходу.','compatible_clarification','Мінімально назвати наступну зустріч за маршрутом і відмову давати домашню адресу для обходу/запису. Не вигадувати нової домівки чи розширеного доступу.',['CH08 contactscope','Taras manualroute'])
add(['gemini_pro:turn-001:4'],'voice','minor','taste',[185],'Образився на полегшення','Уособлення власної реакції — точний сухий гумор Даля; займенник має ясний найближчий референт.','preserve_context','Зберегти.')
add(['gemini_pro:turn-002:3'],'clarity','minor','strong_inference',[917],'Налив повз край','Чашка стоїть не там, де звик; герой схибив, а не переповнив її. Локальна точність руху сильніша за загальний нормативний ярлик.','compatible_clarification','Природно показати, що частину води налив повз чашку; зберегти помилку, рукав перед серветкою й гумор технічного ранку.')
add(['terra:final:2'],'knowledge','minor','reader_reaction',[944,978,1804,1850],'Пізній початок розслідування / раніше нагадати Далю дату','Читацьке відчуття допустиме, але Даль не знає дату доCH35. Перенесення його знання раніше порушить архітектуру. Читач може зіставити DOC01іCH14.','preserve_context','Не нагадувати Далю невідомий факт раніше. Не підсилювати доказом змови; лишити поступове отримання витягів.',['reader ahead vs Dal','R1→R2'])
add(['terra:final:3'],'ending','minor','taste',[1794,1838,1884,1894],'Пропозиція окремої післямови','CH35–36 дають окреме запитання після завершеної дружньої дії, а остання сцена знову підтверджує зустріч. Це свідомий відкритий фінал серії, не поломка.','preserve_context','Не виносити глави в післямову і не скорочувати людський фінал заради загадки.')
add(['gemini_flash:turn-001:questions','gemini_flash:turn-002:questions','gemini_flash:turn-003:questions','gemini_pro:interim_questions'],'promise','minor','reader_reaction',[7,820,821,1304,1774,1864],'Проміжні питання про минуле, резерв, L2 та майбутнє руху','Питання сліпого читача не встановлюють травму рук, таємну змову чи нерозкриту смерть Ніни. Лінія тому закінчує домовленість/дружбу; U01–U05 і майбутня заявка не отримують вигаданих відповідей.','preserve_context','Залишити гіпотезами/відкритими залежностями. Не писати повернення професії, зцілення Ніни, пояснення Майї або таємного куратора.')
add(['gemini_pro:turn-002:4','gemini_pro:turn-003:3','gemini_pro:turn-004:3','terra:strengths','gemini_flash:strengths'],'scene','minor','reader_reaction',[879,881,1169,1871,1872],'Позитивні локальні спостереження','Незгода торговця, ціна помилки і відмова від навантаженого питання підтверджені. Похвала не доводить бездоганності всього тому.','preserve_function','Зберегти ці функції, не додавати примирення чи глобального успіху.')
add(['astra:full_read'],'clarity','minor','strong_inference',[1571],'Подивився, чи я справді буду','Погляд не підтверджує майбутню явку; фраза випадково замінює погодження в сцені передачі. Не телепатична система, а неточний дієслівний місток.','compatible_correction','Локально зробити підтвердження явки питанням/звіркою з Далем перед передачею. Не обіцяти гарантованої майбутньої поведінки.',['CH29 twoWednesdaytasks','CH33 payoff'])
add(['root:initialCH01-04','root:native01-06:observations'],'scene','minor','reader_reaction',[48,50,58,148,174,185,213],'Історичні зауваження до Terra v1','Поточнийv2 розігрує звірку/олівець/пакунки, шість прикладів означають екрани добровольців, не шість окремих запитів; три запити не суперечать цьому. relayзамінено контекстним українським ретранслятором.','already_addressed','Не переносити вимогу шести нових мікросцен; старі хеші належатьv1. Не заявляти, що весь текст став довгим: v2 лишається стислим повним романом.')
add(['root:metadata-dependencies','astra:state_crosscheck'],'other','minor','confirmed_conflict',[133,612,761,1373,1776],'Неправильні успадковані U-ID у станах','U05 означає подальші обставини Майї, не години Іри; U01 — ключ/автоматичне відновлення виклику, не будь-який доступ; U03 — причина зовнішнього резерву, не вся невизначеність. Деякі стани використовують їх як загальні мітки.','compatible_metadata','Вилучити тільки нерелевантні зв’язки згідно metadata_updates. Самі U01–U05 лишити unresolved в загальному реєстрі. Не перепризначати ID Ірі.')
add(['astra:state_crosscheck'],'knowledge','minor','confirmed_conflict',[748,761,1361],'СтанCH13 передчасно завершує всі власні копії','У прозіCH13 монтажні копії вилучаються; фінальна перевірка всіх робочих копій підтверджена лишеCH25. knowledgeCH13 каже власні копії прибрано без обмеження.','compatible_metadata','Відділити прибрані публікації/локальну папку від pendingперевірки інших робочих копій. Не міняти прозу чи дату повідомлення редакторки.',['CH13→CH25 copiesknowledge'])

items=[];patches=[]
for k,d in enumerate(DATA,1):
 id=f'ENS-{k:03d}';origroles=[]
 for x in d['orig']:
  a=x.split(':')[0];a={'gemini_pro':'gemini','root':'astra'}.get(a,a)
  if a not in origroles:origroles.append(a)
 locations=[loc[x] for x in d['ps']]
 item=dict(id=id,origin_reports=origroles,provenance=d['orig'],category=d['cat'],severity=d['sev'],certainty=d['certainty'],locations=locations,observation=d['title'],reader_effect=d['why'],evidence='; '.join(f'P{x:05d} CH{loc[x]["chapter"]}' for x in d['ps']),proposed_actions=[d['direction']],dependencies=d['deps'],author_decision=dict(status='pending',basis='No individual author vote invented. Compatible corrections separately within explicit bulk author instruction.'),implementation=dict(status='not_started',targets=[]),verification=dict(status='not_run',evidence=None),adjudication=dict(disposition=d['decision'],rationale=d['why']),agreement='convergent' if len(origroles)>1 else 'single')
 items.append(item)
 if d['decision'] in ['compatible_correction','compatible_clarification']:
  # Only actual edit targets, not supporting evidence, enter the mutation plan.
  targets={5:[544],6:[715],7:[1003,1047],8:[1612],9:[786],10:[774],11:[1615],13:[1545,1717],14:[1660],42:[1571]}.get(k,[d['ps'][0]])
  for n in targets:
   before=paragraphs[n-1];assert SOURCE.read_text(encoding='utf-8').count(before)==1,(id,n)
   chapter=loc[n]['chapter'];patchid=f'B02-FINAL-{len(patches)+1:03d}'
   patches.append(dict(id=patchid,issue_ids=[id],chapter=chapter,anchor=f'P{n:05d}',source_sha256=SHA,before=before,before_sha256=hashlib.sha256(before.encode()).hexdigest(),direction=d['direction'],preserve='POV Dal first person past; existing action/result/voice; no new canon, access, personal disclosures, private foreknowledge or changes outside bounded target.',dependencies=d['deps'],authorization='bulk_authorized_compatible_implementation_not_individual_author_vote',after_authorship='Native Terra writes exact replacement; Astra supplies direction, not imposed prose.'))
   item['implementation']['targets'].append(patchid)
save(P/'issue-ledger.json',dict(schema_version=1,run_id='book02-literary-v1',project_id='kontakt',book_id='book-02',source_sha256=SHA,status='reconciled',author_decisions='All pending; do not infer votes from editor dispositions',items=items))
states=rd(RUN/'terra-full-v2/states/chapters-19-24.json');s20=next(x for x in states['chapters'] if x['chapter']==20)['observed']['scenes'][0]
metadata=[dict(chapter=20,scene_id='B02-CH20-SC01',field='time_basis',before=s20['time_basis'],after='Плановий D7 00:30–02:00; спостережено: частина дії після другої години ночі (після02:00), точний кінець сцени не названо. CH21 прибуття до Лани трохи після07:00.',issue_ids=['ENS-004'],direction='Write to NEW final states only, never mutate frozen v2.')]
allstates={s['id']:(c['chapter'],s) for f in (RUN/'terra-full-v2/states').glob('*.json') for c in rd(f)['chapters'] for s in c['observed']['scenes']}
depupdates={'B02-CH02-SC01':[],'B02-CH06-SC01':[],'B02-CH13-SC01':[],'B02-CH14-SC02':['U05'],'B02-CH16-SC01':[],'B02-CH25-SC01':[],'B02-CH26-SC01':[],'B02-CH31-SC01':[],'B02-CH34-SC01':['U03']}
for sid,after in depupdates.items():
 chapter,s=allstates[sid];metadata.append(dict(chapter=chapter,scene_id=sid,field='open_dependencies',before=s['open_dependencies'],after=after,issue_ids=['ENS-044'],direction='Remove irrelevant inherited ID only; all unresolved questions remain in global proposed registry. Root may apply this array update mechanically to NEW version.'))
sid='B02-CH13-SC01';chapter,s=allstates[sid]
metadata.append(dict(chapter=13,scene_id=sid,field='knowledge',before=s['knowledge'],after='Даль, Тарас і Вектор знають Ірину пряму вимогу та фактичне прибрання власної публікації/посилань і локальної монтажної папки. Вилучення й перевірка решти робочих копій ще тривають; сторонні копії не підконтрольні. Іра отримала саме цей обмежений звіт. Завершення перевірки всіх робочих копій стане відомим Далю лише з повідомлення монтажерки CH25.',issue_ids=['ENS-045'],direction='Bound knowledge to actual prose; no full-deletion claim atCH13.'))
for chapter,desc in [(9,'Earlier volunteer contact pending; single refusal in corridor; two gaps remain.'),(12,'Playback/withdrawal D4 Friday; recorded debate D2 Wednesday.'),(13,'Misleading hypothetical message loss refers to experiment, not Saturday launch.'),(18,'Explicit D7 Monday00 launch /D8 Tuesday00 return.'),(19,'Explicit Tuesday00 return, launchMonday00.'),(29,'Distinct Wednesday table case + actual confirmation of Dal availability.'),(30,'PostTuesday00:30 invitation for sameTuesday12; Vector formal address.'),(31,'Dal declined before broadcast, not left midbroadcast.'),(33,'Wednesday table case distinct from Monday completed Lana handover.')]:
 metadata.append(dict(chapter=chapter,scene_id=f'B02-CH{chapter:02d}-SC01',field='affected observed events/knowledge/time/resources and proof quotes',direction=desc+' Update only fields affected by final prose; all chapter/new source hashes, quote anchors and derived maps regenerated.'))
save(P/'PATCH-PLAN.json',dict(status='ready_for_native_terra_final_corrections',source=str(SOURCE.relative_to(ROOT)).replace('\\','/'),source_sha256=SHA,author_scope='Explicit all-reviews compatible final correction. No per-item fabricated vote. Preserve v2 and create new final version.',patches=patches,metadata_updates=metadata,global_preserve=['All36 chapters and DOC01 afterCH17 heading','No ending restructure or foreknowledge/mole proof','U01–U05 unresolved; new details remain working proposals','One exact L1+B local24hoperation; L2 never authorized','Reader ahead fromDOC01; Dal knowsdateonlyCH35','Ira ownagency/oldoutsidecopy notnewVectorbreach','Taras friendship afterboringwork notnewmovement'],verification_required=['Exact sourceSHA before apply','Each before unique in source/chapter; no overlapping patches','Terra exact replacement and stateupdates authored','Read changed whole paragraphs and dependent passages','Reassemble36, newanchors/sourcehash, states/proposals/change-log, checks and readerDOCX','No fixed review overwritten or made authorcanon']))
notes=rd(P/'reading-notes.json');notes['status']='complete';notes['fully_read_chapters']=list(range(1,37));notes['last_read_anchor']='P01894';notes['scope']='All1894 source blocks in36chapters actually displayed and read sequentially in12 untruncated batches of3chapters during reconciliation; reports read first so this is nonblind editorial reconciliation, not independent Astra diagnosis.'
notes['notes']=[n for n in notes['notes'] if max(n['chapters'])<=15]
notes['notes'] += [dict(chapters=[16,17,18],literary='Visibilityreward contrasts boundedBallast/privatepracticalhelp; reader-onlyDOC gives earlierdate, Dalaggregatehypothesis remainsunverified; signaturesandpublicpair20:10 staged.',findings=['P01003 returntomorrowwrongpreSundaymidnight; explicitMonday/Tuesday needed.']),dict(chapters=[19,20,21],literary='Crowdtemptation and actualoperatorlaunch; chairfailurecounterbalancescompletedfabric; daytime laborcost enacted without catastrophe.',findings=['P01026 typo','P01041 spoonverb','P01047 returncalendar','P01119 after02 boundary notmetadata']),dict(chapters=[22,23,24],literary='Repetitionadvantage persists withoutbadactors; Lanas transparentqueues practicalfilter; VectortriesactualL2andacceptsexplicitrefusal, stillambitious.',findings=['P01272 completedMondayrecipientfemale; compareWednesdaycase, notautomaticcontradiction']),dict(chapters=[25,26,27],literary='Privateabsenceuncertainnotdanger; staffcopiesconfirmed; DalleavesBEFOREbroadcastandknowsresultviapresenter; Iras ownSundayhoursandscopehold.',findings=['P01358 datecollocation','Tarasprivate ты contextual','P01420 compactlocalpolish; CH31timingmustmatch']),dict(chapters=[28,29,30],literary='Food/mistaken sauces allowpausewithouttherapy; namedunfinishedtasks; extensionrefused, timerreturnswithmixedresponsesnotvote.',findings=['P01545/1717 distinguishWednesdaytable','P01571 lookedifwillcome awkwardconfirmation','P01612 sameTuesdayinvitation','P01615 Vectorregister']),dict(chapters=[31,32,33],literary='Boundedreport retainedlosses; materialjoboffer refusal costsfuture; Wednesdayroutineendsbeforestaydecision. AdaptertransferredThursdaynotfalselycompleted.',findings=['P01660 beforevsmidbroadcast','P01667 apostrophe','P01717/1738 tableclarityonly','Pro claim finishedtablefalse: P01743 iffinish']),dict(chapters=[34,35,36],literary='Friendshipaskedafterwork; Ninaremainsoldloss; Ballasttypedonly. Narrowlegalexternalrecordandlocalordercheck; threehypotheses, normalfriendmeetingnotrecruitment.',findings=['Do notmoveDaldateknowledgeearlier','Do notmarkcodaafterword','P01821 contextualellipsis andP01824dativepreserve'])]
save(P/'reading-notes.json',notes)
coverage=[]
for r in ranges:
 f=RUN/'terra-full-v2/chapters'/f'chapter-{r["chapter"]:02d}.md';coverage.append(dict(**r,source=str(f.relative_to(ROOT)).replace('\\','/'),sha256=sha(f),reading='complete_actual_sequential_nonblind',first_quote=paragraphs[r['first_paragraph']-1],last_quote=paragraphs[r['last_paragraph']-1],notes_ref='reading-notes.json'))
save(P/'reading-coverage.json',dict(source_sha256=SHA,blocks_read=1894,unread_blocks=0,chapters=coverage,context_note='Prior rough authorship is background, not counted as this full v2 reading. No full Book1 reread claimed.'))
save(P/'actual-paragraph-map.json',dict(source_sha256=SHA,paragraph_convention='Nonempty double-newline blocks of exact source; DOC01 remains one block.',chapters=ranges))
print(json.dumps(dict(items=len(items),patches=len(patches),metadata_updates=len(metadata),dispositions=dict(collections.Counter(x['adjudication']['disposition'] for x in items)))))
